name: CI & Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

permissions:
  contents: read    # per checkout e fetch
  packages: write   # per pubblicare su GitHub Packages

jobs:
  test:
    name: 🧪 Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test --configuration Release --no-build --no-restore

  pack-and-publish:
    name: 📦 Pack & Publish
    needs: test
    # scatta SOLO su push di tag v*
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: "Debug: stampa ref"
        run: |
          echo "EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_REF:   $GITHUB_REF"
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Pack NuGet package
        run: |
          dotnet pack BlazorWindKit.Core/BlazorWindKit.Core.csproj \
            --configuration Release \
            --no-build \
            --output ./artifacts \
            /p:PackageVersion=${{ github.ref_name }}

      - name: Configure GitHub Packages source
        run: |
          dotnet nuget add source \
            --username ${{ github.actor }} \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text \
            --name github \
            "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Publish to GitHub Packages
        run: |
          dotnet nuget push ./artifacts/*.nupkg \
            --source github \
            --api-key ${{ secrets.GITHUB_TOKEN }}
